name: 'carbon_pulse'
version: '0.1.0'
config-version: 2

profile: 'carbon_pulse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  carbon_pulse:
    staging:
      +materialized: view
    marts:
      +materialized: table
    core:
      +materialized: table

vars:
  carbon_pulse:
    # Variables for the project
    low_carbon_threshold: 200
    high_carbon_threshold: 400 